server:
    port: 8080
    servlet:
        context-path: /food-delivery

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/food_delivery_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect